/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/dance.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.dance.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="a_(7)" geometry={nodes['a_(7)'].geometry} material={materials['a (7)']} skeleton={nodes['a_(7)'].skeleton} />
          <skinnedMesh name="a_(8)" geometry={nodes['a_(8)'].geometry} material={materials['a (8)']} skeleton={nodes['a_(8)'].skeleton} />
          <skinnedMesh name="a_(8)001" geometry={nodes['a_(8)001'].geometry} material={materials['a (8)']} skeleton={nodes['a_(8)001'].skeleton} />
          <skinnedMesh name="Cone" geometry={nodes.Cone.geometry} material={materials['Material.014']} skeleton={nodes.Cone.skeleton} />
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.013']} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['skin.001']} skeleton={nodes.Cube002.skeleton} />
          <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['green.003']} skeleton={nodes.Cube003.skeleton} />
          <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['green.004']} skeleton={nodes.Cube004.skeleton} />
          <skinnedMesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.013']} skeleton={nodes.Cube006.skeleton} />
          <skinnedMesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.016']} skeleton={nodes.Cube007.skeleton} />
          <group name="Cube008">
            <skinnedMesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['green.005']} skeleton={nodes.Cube014.skeleton} />
            <skinnedMesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials['wire_008061138.002']} skeleton={nodes.Cube014_1.skeleton} />
            <skinnedMesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials['green.008']} skeleton={nodes.Cube014_2.skeleton} />
          </group>
          <skinnedMesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.016']} skeleton={nodes.Cube010.skeleton} />
          <group name="Cube011">
            <skinnedMesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['green.005']} skeleton={nodes.Cube018.skeleton} />
            <skinnedMesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials['wire_008061138.002']} skeleton={nodes.Cube018_1.skeleton} />
            <skinnedMesh name="Cube018_2" geometry={nodes.Cube018_2.geometry} material={materials['green.008']} skeleton={nodes.Cube018_2.skeleton} />
          </group>
          <skinnedMesh name="Cube082" geometry={nodes.Cube082.geometry} material={nodes.Cube082.material} skeleton={nodes.Cube082.skeleton} />
          <skinnedMesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['skin.001']} skeleton={nodes.Cylinder001.skeleton} />
          <skinnedMesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['green.004']} skeleton={nodes.Cylinder002.skeleton} />
          <skinnedMesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['green.004']} skeleton={nodes.Cylinder003.skeleton} />
          <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['skin.001']} skeleton={nodes.Cylinder004.skeleton} />
          <skinnedMesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['green.004']} skeleton={nodes.Plane002.skeleton} />
          <skinnedMesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['skin.001']} skeleton={nodes.Sphere002.skeleton} />
          <skinnedMesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials['skin.001']} skeleton={nodes.Sphere004.skeleton} />
          <skinnedMesh name="Torus003" geometry={nodes.Torus003.geometry} material={materials['green.004']} skeleton={nodes.Torus003.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dance.glb')
